"""Sandbox v2 Store Interface — Protocol 定义。

定义 Sandbox v2 持久化接口，便于后续替换为 PostgreSQL。
当前默认实现：src/adapters/sqlite_sandbox_v2_store.py
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.open_platform.sandbox_v2.models import (
    SandboxJob,
    SandboxV2ExecutionRecord,
    SandboxV2JobStatus,
    SandboxArtifact,
    SandboxArtifactManifest,
    SandboxPackageRequest,
    SandboxPackageQuarantineRecord,
    SandboxPackageSBOM,
    SandboxPackageVulnerabilityScanResult,
    SandboxNetworkEgressRequest,
    SandboxNetworkEgressAuditRecord,
    SandboxIsolationCapability,
    SandboxExecutionPlan,
    SandboxContainerExecutionPlan,
    SandboxContainerExecutionResult,
    SandboxKillRequest,
    SandboxKillRecord,
    SandboxActiveExecutionHandle,
    SandboxV2AuditEvent,
    SandboxV2EvidenceBundle,
    SandboxV2AccessDecision,
    SandboxV2BenchmarkConfig,
    SandboxV2BenchmarkResult,
    SandboxV2CapacityEstimate,
    SandboxV2IAMProviderConfig,
    SandboxV2ExternalIdentity,
    SandboxV2IAMRoleMapping,
    SandboxV2IAMMappingDecision,
    SandboxV2SSOSimulationResult,
    SandboxV2TraceSpan,
    SandboxV2TelemetryExportRecord,
    SandboxV2GrafanaDashboardSpec,
    SandboxV2LoadTestConfig,
    SandboxV2LoadTestResult,
    SandboxV2SLODefinition,
    SandboxV2SLOEvaluation,
    SandboxV2CapacityPlan,
)


@runtime_checkable
class SandboxV2Store(Protocol):
    """Sandbox v2 持久化接口 Protocol。

    方法签名设计为便于后续替换为 PostgreSQL 实现。
    """

    # ── Job ──

    def create_job(self, job: SandboxJob) -> SandboxJob:
        """创建 job，返回带有持久化 job_id 的 job。"""
        ...

    def get_job(self, job_id: str) -> SandboxJob | None:
        """按 job_id 查询。"""
        ...

    def list_jobs(
        self,
        organization_id: str | None = None,
        workspace_id: str | None = None,
        limit: int = 50,
    ) -> list[SandboxJob]:
        """列出 jobs，可按 organization_id / workspace_id 筛选。"""
        ...

    def update_job_status(self, job_id: str, status: str) -> SandboxJob | None:
        """更新 job 状态，返回更新后的 job 或 None。"""
        ...

    # ── Execution Record ──

    def create_execution_record(self, record: SandboxV2ExecutionRecord) -> SandboxV2ExecutionRecord:
        """创建执行记录。"""
        ...

    def get_execution_record(self, record_id: str) -> SandboxV2ExecutionRecord | None:
        """按 record_id 查询。"""
        ...

    def list_execution_records(
        self,
        job_id: str | None = None,
        limit: int = 50,
    ) -> list[SandboxV2ExecutionRecord]:
        """列出执行记录，可按 job_id 筛选。"""
        ...

    # ── Artifact (Step 3) ──

    def create_artifact(self, artifact: SandboxArtifact) -> SandboxArtifact:
        """创建 artifact metadata 记录。"""
        ...

    def get_artifact(self, artifact_id: str) -> SandboxArtifact | None:
        """按 artifact_id 查询。"""
        ...

    def list_artifacts(
        self,
        job_id: str | None = None,
        record_id: str | None = None,
        organization_id: str | None = None,
        workspace_id: str | None = None,
        limit: int = 50,
    ) -> list[SandboxArtifact]:
        """列出 artifacts。"""
        ...

    def update_artifact_status(self, artifact_id: str, status: str) -> SandboxArtifact | None:
        """更新 artifact 状态。"""
        ...

    def create_artifact_manifest(self, manifest: SandboxArtifactManifest) -> SandboxArtifactManifest:
        """创建 artifact manifest。"""
        ...

    def get_artifact_manifest(self, manifest_id: str) -> SandboxArtifactManifest | None:
        """按 manifest_id 查询。"""
        ...

    def list_artifact_manifests(
        self,
        job_id: str | None = None,
        record_id: str | None = None,
        limit: int = 50,
    ) -> list[SandboxArtifactManifest]:
        """列出 artifact manifests。"""
        ...

    def mark_artifact_expired(self, artifact_id: str) -> SandboxArtifact | None:
        """标记 artifact 为过期。"""
        ...

    def delete_artifact_metadata(self, artifact_id: str) -> bool:
        """删除 artifact metadata 记录。"""
        ...

    # ── Package / Supply Chain (Step 4) ──

    def create_package_request(self, request: SandboxPackageRequest) -> SandboxPackageRequest:
        ...

    def get_package_request(self, package_request_id: str) -> SandboxPackageRequest | None:
        ...

    def list_package_requests(
        self, job_id: str | None = None, organization_id: str | None = None,
        workspace_id: str | None = None, status: str | None = None, limit: int = 50,
    ) -> list[SandboxPackageRequest]:
        ...

    def update_package_request_status(self, package_request_id: str, status: str, reason: str = "") -> SandboxPackageRequest | None:
        ...

    def create_quarantine_record(self, record: SandboxPackageQuarantineRecord) -> SandboxPackageQuarantineRecord:
        ...

    def get_quarantine_record(self, quarantine_id: str) -> SandboxPackageQuarantineRecord | None:
        ...

    def list_quarantine_records(self, package_request_id: str | None = None, status: str | None = None, limit: int = 50) -> list[SandboxPackageQuarantineRecord]:
        ...

    def update_quarantine_status(self, quarantine_id: str, status: str, reason: str = "") -> SandboxPackageQuarantineRecord | None:
        ...

    def create_package_sbom(self, sbom: SandboxPackageSBOM) -> SandboxPackageSBOM:
        ...

    def get_package_sbom(self, sbom_id: str) -> SandboxPackageSBOM | None:
        ...

    def list_package_sboms(self, package_request_id: str | None = None, limit: int = 50) -> list[SandboxPackageSBOM]:
        ...

    def create_vulnerability_scan_result(self, result: SandboxPackageVulnerabilityScanResult) -> SandboxPackageVulnerabilityScanResult:
        ...

    def get_vulnerability_scan_result(self, scan_id: str) -> SandboxPackageVulnerabilityScanResult | None:
        ...

    def list_vulnerability_scan_results(self, package_request_id: str | None = None, limit: int = 50) -> list[SandboxPackageVulnerabilityScanResult]:
        ...

    # ── Network Egress (Step 5) ──

    def create_network_egress_request(self, request: SandboxNetworkEgressRequest) -> SandboxNetworkEgressRequest:
        ...

    def get_network_egress_request(self, egress_request_id: str) -> SandboxNetworkEgressRequest | None:
        ...

    def list_network_egress_requests(self, job_id: str | None = None, organization_id: str | None = None, workspace_id: str | None = None, status: str | None = None, limit: int = 50) -> list[SandboxNetworkEgressRequest]:
        ...

    def update_network_egress_request_status(self, egress_request_id: str, status: str, reason: str = "") -> SandboxNetworkEgressRequest | None:
        ...

    def create_network_egress_audit_record(self, record: SandboxNetworkEgressAuditRecord) -> SandboxNetworkEgressAuditRecord:
        ...

    def get_network_egress_audit_record(self, audit_id: str) -> SandboxNetworkEgressAuditRecord | None:
        ...

    def list_network_egress_audit_records(self, egress_request_id: str | None = None, job_id: str | None = None, limit: int = 50) -> list[SandboxNetworkEgressAuditRecord]:
        ...

    # ── Isolation / Execution Plan (Step 6A) ──

    def create_isolation_capability(self, capability: SandboxIsolationCapability) -> SandboxIsolationCapability:
        ...

    def get_latest_isolation_capability(self, provider: str | None = None) -> SandboxIsolationCapability | None:
        ...

    def list_isolation_capabilities(self, provider: str | None = None, limit: int = 50) -> list[SandboxIsolationCapability]:
        ...

    def create_execution_plan(self, plan: SandboxExecutionPlan) -> SandboxExecutionPlan:
        ...

    def get_execution_plan(self, execution_plan_id: str) -> SandboxExecutionPlan | None:
        ...

    def list_execution_plans(self, job_id: str | None = None, organization_id: str | None = None, workspace_id: str | None = None, status: str | None = None, limit: int = 50) -> list[SandboxExecutionPlan]:
        ...

    def update_execution_plan_status(self, execution_plan_id: str, status: str, reason: str = "") -> SandboxExecutionPlan | None:
        ...

    # ── Container Execution (Step 6B) ──
    def create_container_execution_plan(self, plan: SandboxContainerExecutionPlan) -> SandboxContainerExecutionPlan: ...
    def get_container_execution_plan(self, container_plan_id: str) -> SandboxContainerExecutionPlan | None: ...
    def list_container_execution_plans(self, job_id: str | None = None, status: str | None = None, limit: int = 50) -> list[SandboxContainerExecutionPlan]: ...
    def update_container_execution_plan_status(self, container_plan_id: str, status: str, reason: str = "") -> SandboxContainerExecutionPlan | None: ...
    def create_container_execution_result(self, result: SandboxContainerExecutionResult) -> SandboxContainerExecutionResult: ...
    def get_container_execution_result(self, container_result_id: str) -> SandboxContainerExecutionResult | None: ...
    def list_container_execution_results(self, job_id: str | None = None, container_plan_id: str | None = None, limit: int = 50) -> list[SandboxContainerExecutionResult]: ...

    # ── Kill Switch (Step 7) ──
    def create_kill_request(self, request: SandboxKillRequest) -> SandboxKillRequest: ...
    def get_kill_request(self, kill_request_id: str) -> SandboxKillRequest | None: ...
    def list_kill_requests(self, job_id: str | None = None, status: str | None = None, limit: int = 50) -> list[SandboxKillRequest]: ...
    def update_kill_request_status(self, kill_request_id: str, status: str, reason: str = "") -> SandboxKillRequest | None: ...
    def create_kill_record(self, record: SandboxKillRecord) -> SandboxKillRecord: ...
    def get_kill_record(self, kill_record_id: str) -> SandboxKillRecord | None: ...
    def list_kill_records(self, job_id: str | None = None, kill_request_id: str | None = None, limit: int = 50) -> list[SandboxKillRecord]: ...
    def create_active_execution_handle(self, handle: SandboxActiveExecutionHandle) -> SandboxActiveExecutionHandle: ...
    def get_active_execution_handle(self, handle_id: str) -> SandboxActiveExecutionHandle | None: ...
    def get_active_execution_handle_for_job(self, job_id: str) -> SandboxActiveExecutionHandle | None: ...
    def list_active_execution_handles(self, status: str | None = None, limit: int = 50) -> list[SandboxActiveExecutionHandle]: ...
    def update_active_execution_handle_status(self, handle_id: str, status: str, reason: str = "") -> SandboxActiveExecutionHandle | None: ...
    def mark_active_execution_cancel_requested(self, handle_id: str, reason: str) -> SandboxActiveExecutionHandle | None: ...

    # ── MicroVM Execution (Step 11) ──
    def create_microvm_execution_plan(self, plan: Any) -> Any: ...
    def get_microvm_execution_plan(self, microvm_plan_id: str) -> Any | None: ...
    def list_microvm_execution_plans(self, job_id: str | None = None, status: str | None = None, limit: int = 50) -> list[Any]: ...
    def update_microvm_execution_plan_status(self, microvm_plan_id: str, status: str, reason: str = "") -> Any | None: ...
    def create_microvm_execution_result(self, result: Any) -> Any: ...
    def get_microvm_execution_result(self, microvm_result_id: str) -> Any | None: ...
    def list_microvm_execution_results(self, job_id: str | None = None, microvm_plan_id: str | None = None, limit: int = 50) -> list[Any]: ...

    # ── Security / Audit (Step 14) ──
    def create_security_audit_event(self, event: SandboxV2AuditEvent) -> SandboxV2AuditEvent: ...
    def get_security_audit_event(self, audit_event_id: str) -> SandboxV2AuditEvent | None: ...
    def get_latest_security_audit_event(self, organization_id: str | None = None, workspace_id: str | None = None) -> SandboxV2AuditEvent | None: ...
    def list_security_audit_events(self, organization_id: str | None = None, workspace_id: str | None = None, event_type: str | None = None, severity: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_evidence_bundle(self, bundle: SandboxV2EvidenceBundle) -> SandboxV2EvidenceBundle: ...
    def get_evidence_bundle(self, evidence_bundle_id: str) -> SandboxV2EvidenceBundle | None: ...
    def list_evidence_bundles(self, organization_id: str | None = None, workspace_id: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_access_decision_record(self, decision: SandboxV2AccessDecision) -> SandboxV2AccessDecision: ...
    def list_access_decision_records(self, organization_id: str | None = None, workspace_id: str | None = None, limit: int = 50) -> list[Any]: ...

    # ── Monitoring / Alerts / Health (Step 15) ──
    def create_metric_sample(self, sample: Any) -> Any: ...
    def list_metric_samples(self, name: str | None = None, organization_id: str | None = None, workspace_id: str | None = None, limit: int = 100) -> list[Any]: ...
    def create_metrics_snapshot(self, snapshot: Any) -> Any: ...
    def get_latest_metrics_snapshot(self, organization_id: str | None = None, workspace_id: str | None = None) -> Any | None: ...
    def list_metrics_snapshots(self, organization_id: str | None = None, workspace_id: str | None = None, limit: int = 20) -> list[Any]: ...
    def create_alert_rule(self, rule: Any) -> Any: ...
    def list_alert_rules(self, organization_id: str | None = None, workspace_id: str | None = None, enabled: bool | None = None, limit: int = 100) -> list[Any]: ...
    def create_alert(self, alert: Any) -> Any: ...
    def get_alert(self, alert_id: str) -> Any | None: ...
    def list_alerts(self, status: str | None = None, severity: str | None = None, organization_id: str | None = None, workspace_id: str | None = None, limit: int = 100) -> list[Any]: ...
    def update_alert_status(self, alert_id: str, status: str, reason: str = "", actor: str = "") -> Any | None: ...
    def create_health_check_result(self, result: Any) -> Any: ...
    def list_health_check_results(self, component: str | None = None, limit: int = 100) -> list[Any]: ...
    def get_latest_health_check_results(self) -> list[Any]: ...

    # ── Real OIDC / SAML (Step 20) ──
    def create_sso_state(self, state: Any) -> Any: ...
    def get_sso_state(self, sso_state_id: str) -> Any | None: ...
    def get_sso_state_by_hash(self, state_hash: str) -> Any | None: ...
    def consume_sso_state(self, sso_state_id: str) -> Any | None: ...
    def create_oidc_auth_request(self, request: Any) -> Any: ...
    def list_oidc_auth_requests(self, provider_config_id: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_oidc_callback_result(self, result: Any) -> Any: ...
    def list_oidc_callback_results(self, provider_config_id: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_oidc_token_validation_result(self, result: Any) -> Any: ...
    def create_saml_auth_request(self, request: Any) -> Any: ...
    def list_saml_auth_requests(self, provider_config_id: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_saml_acs_result(self, result: Any) -> Any: ...
    def list_saml_acs_results(self, provider_config_id: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_sso_session(self, session: Any) -> Any: ...
    def get_sso_session(self, session_id: str) -> Any | None: ...
    def list_sso_sessions(self, organization_id: str | None = None, workspace_id: str | None = None, status: str | None = None, limit: int = 50) -> list[Any]: ...
    def revoke_sso_session(self, session_id: str, reason: str | None = None) -> Any | None: ...

    # ── Load Testing / SLO (Step 19) ──
    def create_load_test_config(self, config: Any) -> Any: ...
    def get_load_test_config(self, load_test_id: str) -> Any | None: ...
    def list_load_test_configs(self, limit: int = 50) -> list[Any]: ...
    def create_load_test_result(self, result: Any) -> Any: ...
    def list_load_test_results(self, load_test_id: str | None = None, target: str | None = None, limit: int = 100) -> list[Any]: ...
    def create_slo_definition(self, slo: Any) -> Any: ...
    def list_slo_definitions(self, enabled: bool | None = None, limit: int = 100) -> list[Any]: ...
    def create_slo_evaluation(self, evaluation: Any) -> Any: ...
    def list_slo_evaluations(self, load_test_id: str | None = None, slo_id: str | None = None, limit: int = 100) -> list[Any]: ...
    def create_capacity_plan(self, plan: Any) -> Any: ...
    def get_latest_capacity_plan(self) -> Any | None: ...
    def list_capacity_plans(self, limit: int = 20) -> list[Any]: ...

    # ── Observability (Step 18) ──
    def create_trace_span(self, span: Any) -> Any: ...
    def update_trace_span(self, span_id: str, status: str, finished_at: Any = None, duration_ms: int = 0, metadata: dict[str, Any] | None = None) -> Any | None: ...
    def list_trace_spans(self, organization_id: str | None = None, workspace_id: str | None = None, trace_id: str | None = None, limit: int = 100) -> list[Any]: ...
    def create_telemetry_export_record(self, record: Any) -> Any: ...
    def list_telemetry_export_records(self, provider: str | None = None, signal_type: str | None = None, status: str | None = None, limit: int = 100) -> list[Any]: ...
    def create_grafana_dashboard_spec(self, spec: Any) -> Any: ...
    def get_latest_grafana_dashboard_spec(self) -> Any | None: ...
    def list_grafana_dashboard_specs(self, limit: int = 20) -> list[Any]: ...

    # ── IAM / SSO (Step 17) ──
    def create_iam_provider_config(self, config: Any) -> Any: ...
    def get_iam_provider_config(self, provider_config_id: str) -> Any | None: ...
    def list_iam_provider_configs(self, organization_id: str | None = None, workspace_id: str | None = None, enabled: bool | None = None, limit: int = 50) -> list[Any]: ...
    def update_iam_provider_config_status(self, provider_config_id: str, enabled: bool, reason: str = "") -> Any | None: ...
    def create_external_identity(self, identity: Any) -> Any: ...
    def get_external_identity(self, external_identity_id: str) -> Any | None: ...
    def list_external_identities(self, organization_id: str | None = None, workspace_id: str | None = None, provider_config_id: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_iam_role_mapping(self, mapping: Any) -> Any: ...
    def list_iam_role_mappings(self, provider_config_id: str | None = None, organization_id: str | None = None, workspace_id: str | None = None, enabled: bool | None = None, limit: int = 50) -> list[Any]: ...
    def create_iam_mapping_decision(self, decision: Any) -> Any: ...
    def list_iam_mapping_decisions(self, organization_id: str | None = None, workspace_id: str | None = None, limit: int = 50) -> list[Any]: ...
    def create_sso_simulation_result(self, result: Any) -> Any: ...
    def list_sso_simulation_results(self, organization_id: str | None = None, workspace_id: str | None = None, limit: int = 50) -> list[Any]: ...

    # ── Performance / Capacity (Step 16) ──
    def create_benchmark_config(self, config: SandboxV2BenchmarkConfig) -> SandboxV2BenchmarkConfig: ...
    def get_benchmark_config(self, benchmark_id: str) -> SandboxV2BenchmarkConfig | None: ...
    def list_benchmark_configs(self, limit: int = 50) -> list[SandboxV2BenchmarkConfig]: ...
    def create_benchmark_result(self, result: SandboxV2BenchmarkResult) -> SandboxV2BenchmarkResult: ...
    def list_benchmark_results(self, benchmark_id: str | None = None, target: str | None = None, limit: int = 100) -> list[SandboxV2BenchmarkResult]: ...
    def create_capacity_estimate(self, estimate: SandboxV2CapacityEstimate) -> SandboxV2CapacityEstimate: ...
    def get_latest_capacity_estimate(self) -> SandboxV2CapacityEstimate | None: ...
    def list_capacity_estimates(self, limit: int = 20) -> list[SandboxV2CapacityEstimate]: ...
