"""Memory domain models.

These models define the contract for the multi-layer memory engine and are
surfaced directly in the OpenAPI schema generated by FastAPI.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class MemoryScope(str, Enum):
    """Layered memory taxonomy.

    EPISODIC: event / interaction-bound memories (what happened, when, where).
    SEMANTIC: distilled facts / knowledge (what is true, independent of context).
    """

    EPISODIC = "episodic"
    SEMANTIC = "semantic"


class MemoryItem(BaseModel):
    """Canonical memory record returned by the engine and stored as metadata."""

    model_config = ConfigDict(use_enum_values=False)

    id: str = Field(..., description="Stable identifier (Chroma document id).")
    content: str = Field(..., description="Raw memory text.")
    scope: MemoryScope = Field(..., description="Memory layer this record belongs to.")
    importance: float = Field(
        default=1.0, ge=0.0, le=1.0,
        description="Salience weight in [0, 1] used for reranking.",
    )
    timestamp: datetime = Field(
        ..., description="UTC timestamp at which the memory was written.",
    )


class MemoryWriteRequest(BaseModel):
    """Request body for POST /memory/write."""

    content: str = Field(..., min_length=1, description="Memory text to persist.")
    scope: MemoryScope = Field(
        default=MemoryScope.EPISODIC,
        description="Target memory layer.",
    )
    importance: float = Field(
        default=1.0, ge=0.0, le=1.0,
        description="Salience weight; higher values survive reranking better.",
    )


class MemoryWriteResponse(BaseModel):
    """Response body for POST /memory/write."""

    id: str = Field(..., description="Identifier of the newly stored memory.")
    scope: MemoryScope
    importance: float
    timestamp: datetime
    status: str = Field(default="stored", description="Outcome flag.")


class MemorySearchRequest(BaseModel):
    """Request body for POST /memory/search."""

    query: str = Field(..., min_length=1, description="Natural-language recall query.")
    top_k: int = Field(default=5, ge=1, le=50, description="Maximum hits to return.")
    rerank: bool = Field(
        default=False,
        description="When true, the engine over-fetches and applies mock reranking.",
    )
    scope: Optional[MemoryScope] = Field(
        default=None,
        description="Restrict search to a single layer. None searches all layers.",
    )


class MemorySearchHit(MemoryItem):
    """A memory item augmented with a relevance score."""

    score: float = Field(
        ...,
        description="Relevance score. Higher is more similar. Exact range depends "
        "on the underlying distance metric (cosine by default).",
    )


class MemorySearchResponse(BaseModel):
    """Response body for POST /memory/search."""

    query: str
    hits: List[MemorySearchHit] = Field(default_factory=list)
    total: int = Field(default=0, ge=0)
    reranked: bool = Field(
        default=False, description="Whether the mock reranker was applied.",
    )
